# Generated by Django 4.0.4 on 2022-10-31 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('csv_file', models.FileField(upload_to='forum-csv-files/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
